baseURL = 'in-Diffusion_models/'
languageCode = 'en-us'
title = 'From Physical diffusion to Diffusion Models'
theme = 'PaperMod'


[params]
	defaultTheme="dark"
	ShowReadingTime = true
	ShowCodeCopyButtons = true

	math = true

